### ISSUE TITLE
`AssertsChexifyTest.test_uninspected_checks` test failure

### ISSUE THREAD

**Issue by samuela** [deepmind/chex#204]
I'm seeing the following test failure when running the test suite:
```
============================= test session starts ==============================
platform linux -- Python 3.10.7, pytest-7.1.3, pluggy-1.0.0
rootdir: /build/source
collected 548 items                                                            

chex/chex_test.py .                                                      [  0%]
chex/_src/asserts_chexify_test.py ......F.....                           [  2%]
chex/_src/asserts_internal_test.py .s.s.........                         [  4%]
chex/_src/asserts_test.py ..s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s. [ 13%]
s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s..................... [ 26%]
........................................................................ [ 39%]
........................................................................ [ 52%]
.................................                                        [ 58%]
chex/_src/dataclass_test.py ...........................................  [ 66%]
chex/_src/dimensions_test.py .................                           [ 69%]
chex/_src/fake_set_n_cpu_devices_test.py s                               [ 69%]
chex/_src/fake_test.py ................................                  [ 75%]
chex/_src/restrict_backends_test.py ssssssssss                           [ 77%]
chex/_src/variants_test.py .....................s....s............s....s [ 85%]
..........................................................ssssssssssssss [ 98%]
sssssss                                                                  [100%]

=================================== FAILURES ===================================
__________________ AssertsChexifyTest.test_uninspected_checks __________________

self = <chex._src.asserts_chexify_test.AssertsChexifyTest testMethod=test_uninspected_checks>

    def test_uninspected_checks(self):
    
      @jax.jit
      def _pos_sum(x):
        chex_value_assert_positive(x, custom_message='err_label')
        return x.sum()
    
      invalid_x = -jnp.ones(3)
      chexify_async(_pos_sum)(invalid_x)  # async error
    
>     with self.assertRaisesRegex(AssertionError, 'err_label'):
E     AssertionError: AssertionError not raised

chex/_src/asserts_chexify_test.py:179: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  absl:asserts_chexify.py:57 [Chex] Some of chexify assetion statuses were not inspected due to async exec (https://jax.readthedocs.io/en/latest/async_dispatch.html). Consider calling `chex.block_until_chexify_assertions_complete()` at the end of computations that rely on jitted chex assetions.
=============================== warnings summary ===============================
chex/_src/asserts_chexify_test.py: 12 warnings
  /build/source/chex/_src/asserts_chexify_test.py:58: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
    return jnp.all(jnp.array([(x > 0).all() for x in jax.tree_leaves(tree)]))

chex/_src/asserts_chexify_test.py::AssertsChexifyTest::test_static_assertion__with_jit
chex/_src/asserts_chexify_test.py::AssertsChexifyTest::test_static_assertion__without_jit
  /build/source/chex/_src/asserts_chexify_test.py:86: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
    return sum(x.sum() for x in jax.tree_leaves(tree))

chex/_src/asserts_chexify_test.py::AssertsChexifyTest::test_uninspected_checks
  /nix/store/4y9j6xdkgqwkdx5ki508l175smcjgs9l-python3.10-pytest-7.1.3/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in atexit callback: <function _check_if_hanging_assertions at 0x7ffddfe66d40>
  
  Traceback (most recent call last):
    File "/build/source/chex/_src/asserts_chexify.py", line 32, in _check_error
      checkify.check_error(err)
    File "/nix/store/2fcsbc07baqm4mfmibzr1qlh8bfvb6mc-python3.10-jax-0.3.23/lib/python3.10/site-packages/jax/_src/checkify.py", line 476, in check_error
      return assert_p.bind(err, code, payload, msgs=error.msgs)
    File "/nix/store/2fcsbc07baqm4mfmibzr1qlh8bfvb6mc-python3.10-jax-0.3.23/lib/python3.10/site-packages/jax/core.py", line 328, in bind
      return self.bind_with_trace(find_top_trace(args), args, params)
    File "/nix/store/2fcsbc07baqm4mfmibzr1qlh8bfvb6mc-python3.10-jax-0.3.23/lib/python3.10/site-packages/jax/core.py", line 331, in bind_with_trace
      out = trace.process_primitive(self, map(trace.full_raise, args), params)
    File "/nix/store/2fcsbc07baqm4mfmibzr1qlh8bfvb6mc-python3.10-jax-0.3.23/lib/python3.10/site-packages/jax/core.py", line 698, in process_primitive
      return primitive.impl(*tracers, **params)
    File "/nix/store/2fcsbc07baqm4mfmibzr1qlh8bfvb6mc-python3.10-jax-0.3.23/lib/python3.10/site-packages/jax/_src/checkify.py", line 483, in assert_impl
      raise_error(Error(err, code, msgs, payload))
    File "/nix/store/2fcsbc07baqm4mfmibzr1qlh8bfvb6mc-python3.10-jax-0.3.23/lib/python3.10/site-packages/jax/_src/checkify.py", line 123, in raise_error
      raise ValueError(err)
  ValueError: [Chex] chexify assertion failed [err_label] [failed at /build/source/chex/_src/asserts_chexify_test.py:173] (check failed at /build/source/chex/_src/asserts_internal.py:229 (_chex_assert_fn))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/build/source/chex/_src/asserts_chexify.py", line 62, in _check_if_hanging_assertions
      block_until_chexify_assertions_complete()
    File "/build/source/chex/_src/asserts_chexify.py", line 51, in block_until_chexify_assertions_complete
      wait_fn()
    File "/build/source/chex/_src/asserts_chexify.py", line 180, in _wait_checks
      _check_error(async_check_futures.popleft().result(async_timeout))
    File "/build/source/chex/_src/asserts_chexify.py", line 40, in _check_error
      raise AssertionError(msg)  # pylint:disable=raise-missing-from
  AssertionError: [Chex] chexify assertion failed [err_label] [failed at /build/source/chex/_src/asserts_chexify_test.py:173] 
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted
chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted
chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted
chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted_vmapped
chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted_vmapped
  /build/source/chex/_src/asserts_chexify_test.py:52: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
    if not all((x > 0).all() for x in jax.tree_leaves(tree)):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED chex/_src/asserts_chexify_test.py::AssertsChexifyTest::test_uninspected_checks
====== 1 failed, 461 passed, 86 skipped, 20 warnings in 84.47s (0:01:24) =======
error: builder for '/nix/store/f9icjsb9pbz4p8qpsyhp9gq1fvjvwwhz-python3.10-chex-0.1.5.drv' failed with exit code 1;
       last 10 log lines:
       > chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted
       > chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted_vmapped
       > chex/_src/asserts_chexify_test.py::AssertsChexifyTestSuite::test_log_abs_fn_jitted_vmapped
       >   /build/source/chex/_src/asserts_chexify_test.py:52: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
       >     if not all((x > 0).all() for x in jax.tree_leaves(tree)):
       >
       > -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
       > =========================== short test summary info ============================
       > FAILED chex/_src/asserts_chexify_test.py::AssertsChexifyTest::test_uninspected_checks
       > ====== 1 failed, 461 passed, 86 skipped, 20 warnings in 84.47s (0:01:24) =======
```
I'm using 
* jax v0.3.23
* jaxlib v0.3.22
* absl-py v1.2.0
* dm-tree from commit https://github.com/deepmind/tree/commit/b452e5c2743e7489b4ba7f16ecd51c516d7cd8e3
* numpy 1.23.3
* toolz 0.12.0

**Comment by samuela** [comment]
just tested against dm-tree 0.1.7 but still seeing the same error

**Comment by hbq1** [comment]
Hey @samuela, thanks for flagging! It should be fixed now.
