### ISSUE TITLE
Missing package dependency typing-extension

### ISSUE THREAD

**Issue by hylkedonker** [deepmind/chex#259]
Hi,

The latest version (`chex==0.1.7`) is missing the `typing-extension` dependency.
**Problem**
For example, the following python code
```python
from chex import dataclass
```
raises the error
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/chex/__init__.py", line 72, in <module>
    from chex._src.dataclass import dataclass
  File "/usr/local/lib/python3.11/dist-packages/chex/_src/dataclass.py", line 23, in <module>
    from typing_extensions import dataclass_transform  # pytype: disable=not-supported-yet
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'typing_extensions'
```
on ubuntu 23.04 (with Python 3.11)

**Solution**
I found that installing `typing-extension` resolves the error:
```bash
pip3 install typing-extension
```

**Reproduce**
The following code reproduces the error:
```bash
docker run -it ubuntu:23.04 \
  bash -c \
  "apt update && apt install --assume-yes python3-pip && pip3 install --break-system-packages chex && python3 -c 'from chex import dataclass'"
```

**Comment by hbq1** [comment]
Hi @hylkedonker, thanks a lot for raising this issue! It will be fixed in the next release.
